#!/usr/bin/env bash

PID=`ps -ef | grep -e "[t]g_bot" | awk 'FNR == 1 {print $2}'`

if [ -z "$PID" ]; then
    echo "Script is not running."
else
    kill -9 $PID && sleep 1
fi

nohup python3 -m tg_bot > output.log 2>&1 &
echo "Starting Script..."

./status

exit 0
