#!/usr/bin/env bash

PID=`ps -ef | grep -e "[j]oin_captcha_bot.py" | awk 'FNR == 1 {print $2}'`

if [ -z "$PID" ]; then
    echo "Script is not running."
else
    kill -9 $PID && sleep 1
fi


rm -f ./data/captchas/*
nohup python3 -u join_captcha_bot.py > output.log 2>&1 &
echo "Starting Script..."

./status

exit 0
