name: CI
on:
  push:
    branches:
      - 'prod'
      - '!master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy App
        uses: appleboy/ssh-action@v0.1.2
        env:
          FOO: "BAR"
          BAR: "FOO"
          SHA: ${{ secrets.SSH_KEY }}
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "I am $FOO"
            echo "I am $BAR"
            echo "sha: $SHA"