name: CI
on:
  push:
    branches:
      - 'prod'
      - '!master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          hozt: ${{ secrets.SSH_KEY }}
        run: |
          echo $hozt