name: CI
on:
  push:
    branches:
      - 'prod'
      - '!master'

jobs:
  deploy:
    env:
      hozt: ${{secrets:SSH_HOST}}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy App
      - run:
          echo $hozt