name: CI
on:
  push:
    branches:
      - 'prod'
      - '!master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: DeployBot
        run:
          cd /home/ubuntu/telegram-captcha-bot/
          git pull
          cd /home/ubuntu/telegram-captcha-bot/sources/
          ./status
          ./restart